import type { FromSchema } from 'json-schema-to-ts';
import * as schemas from './schemas';
export type CreditCard3DsBodyParam = FromSchema<typeof schemas.CreditCard3Ds.body>;
export type CreditCard3DsResponse200 = FromSchema<typeof schemas.CreditCard3Ds.response['200']>;
export type MbWayBodyParam = FromSchema<typeof schemas.MbWay.body>;
export type MbWayMealPassesBodyParam = FromSchema<typeof schemas.MbWayMealPasses.body>;
export type MbWayMealPassesResponse200 = FromSchema<typeof schemas.MbWayMealPasses.response['200']>;
export type MbWayResponse200 = FromSchema<typeof schemas.MbWay.response['200']>;
export type MultibancoBodyParam = FromSchema<typeof schemas.Multibanco.body>;
export type MultibancoDpgBodyParam = FromSchema<typeof schemas.MultibancoDpg.body>;
export type MultibancoDpgResponse200 = FromSchema<typeof schemas.MultibancoDpg.response['200']>;
export type MultibancoResponse200 = FromSchema<typeof schemas.Multibanco.response['200']>;
export type PaysafecardBodyParam = FromSchema<typeof schemas.Paysafecard.body>;
export type PaysafecardResponse200 = FromSchema<typeof schemas.Paysafecard.response['200']>;
export type PayshopBodyParam = FromSchema<typeof schemas.Payshop.body>;
export type PayshopResponse200 = FromSchema<typeof schemas.Payshop.response['200']>;
export type ReferenceInformationBodyParam = FromSchema<typeof schemas.ReferenceInformation.body>;
export type ReferenceInformationResponse200 = FromSchema<typeof schemas.ReferenceInformation.response['200']>;
